version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      MYSQL_DATABASE: 'bookdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: